version: "3"

services:
  virtual-court-container-1:
    image: virtual-court-data-migration:latest
    privileged: true
    profiles:
     - ${CHUNK_FOLDER_1_PROFILE:-"nomigrate"}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ACCESS_KEY_ID=${ACCESS_KEY_ID:-0}
        - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY:-0}
        - BUCKET_NAME=${BUCKET_NAME:-""}
        - S3_ENDPOINT=${S3_ENDPOINT:-""}
    env_file:
      - .env
    environment:
      - SOURCE_PATH=${CHUNK_FOLDER_1:-""}
    volumes:
      - court-cifs-volume:/mnt/smb
  virtual-court-container-2:
    image: virtual-court-data-migration:latest
    profiles:
     - ${CHUNK_FOLDER_2_PROFILE:-""}
    privileged: true
    env_file:
      - .env
    volumes:
      - court-cifs-volume:/mnt/smb
  virtual-court-container-3:
    image: virtual-court-data-migration:latest
    privileged: true
    profiles:
     - ${CHUNK_FOLDER_3_PROFILE:-"nomigrate"}
    env_file:
      - .env
    environment:
      - SOURCE_PATH=${CHUNK_FOLDER_3:-""}
    volumes:
      - court-cifs-volume:/mnt/smb
  virtual-court-container-4:
    image: virtual-court-data-migration:latest
    privileged: true
    profiles:
     - ${CHUNK_FOLDER_4_PROFILE:-"nomigrate"}
    env_file:
      - .env
    environment:
      - SOURCE_PATH=${CHUNK_FOLDER_4:-""}
    volumes:
      - court-cifs-volume:/mnt/smb
  virtual-court-container-5:
    image: virtual-court-data-migration:latest
    privileged: true
    profiles:
     - ${CHUNK_FOLDER_5_PROFILE:-"nomigrate"}
    env_file:
      - .env
    environment:
      - SOURCE_PATH=${CHUNK_FOLDER_5:-""}
    volumes:
      - court-cifs-volume:{CIFS_PATH}
volumes:
  court-cifs-volume: 
    driver_opts: 
      type: cifs 
      o: "addr=chunk.idir.bcgov,username=${USERNAME},password=${PASSWORD},vers=3.0" 
      device: //chunk.idir.bcgov/5959$